// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: lpr.proto

package lprpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecognizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"` // frame JPEG dari buffer RTSP terakhir
	GateId        string                 `protobuf:"bytes,2,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	CapturedAt    int64                  `protobuf:"varint,3,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"` // epoch ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeRequest) Reset() {
	*x = RecognizeRequest{}
	mi := &file_lpr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeRequest) ProtoMessage() {}

func (x *RecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lpr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeRequest.ProtoReflect.Descriptor instead.
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return file_lpr_proto_rawDescGZIP(), []int{0}
}

func (x *RecognizeRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *RecognizeRequest) GetGateId() string {
	if x != nil {
		return x.GateId
	}
	return ""
}

func (x *RecognizeRequest) GetCapturedAt() int64 {
	if x != nil {
		return x.CapturedAt
	}
	return 0
}

type RecognizeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RawText         string                 `protobuf:"bytes,1,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`                         // output mentah OCR
	NormalizedPlate string                 `protobuf:"bytes,2,opt,name=normalized_plate,json=normalizedPlate,proto3" json:"normalized_plate,omitempty"` // setelah normalisasi plat Indonesia
	Confidence      float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`                                // 0..1
	VehicleType     string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`             // mobil|motor|truk|bus
	Verdict         string                 `protobuf:"bytes,5,opt,name=verdict,proto3" json:"verdict,omitempty"`                                        // AUTO_ACCEPT|NEEDS_REVIEW|UNREAD
	LatencyMs       int32                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	EngineVersion   string                 `protobuf:"bytes,7,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecognizeResponse) Reset() {
	*x = RecognizeResponse{}
	mi := &file_lpr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeResponse) ProtoMessage() {}

func (x *RecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lpr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeResponse.ProtoReflect.Descriptor instead.
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return file_lpr_proto_rawDescGZIP(), []int{1}
}

func (x *RecognizeResponse) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *RecognizeResponse) GetNormalizedPlate() string {
	if x != nil {
		return x.NormalizedPlate
	}
	return ""
}

func (x *RecognizeResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RecognizeResponse) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *RecognizeResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *RecognizeResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *RecognizeResponse) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_lpr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lpr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_lpr_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	EngineVersion string                 `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_lpr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lpr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_lpr_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

var File_lpr_proto protoreflect.FileDescriptor

const file_lpr_proto_rawDesc = "" +
	"\n" +
	"\tlpr.proto\x12\x06lpr.v1\"b\n" +
	"\x10RecognizeRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\x12\x17\n" +
	"\agate_id\x18\x02 \x01(\tR\x06gateId\x12\x1f\n" +
	"\vcaptured_at\x18\x03 \x01(\x03R\n" +
	"capturedAt\"\xfc\x01\n" +
	"\x11RecognizeResponse\x12\x19\n" +
	"\braw_text\x18\x01 \x01(\tR\arawText\x12)\n" +
	"\x10normalized_plate\x18\x02 \x01(\tR\x0fnormalizedPlate\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\x12\x18\n" +
	"\averdict\x18\x05 \x01(\tR\averdict\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x05R\tlatencyMs\x12%\n" +
	"\x0eengine_version\x18\a \x01(\tR\rengineVersion\"\x0f\n" +
	"\rHealthRequest\"G\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion2\x85\x01\n" +
	"\x03LPR\x12@\n" +
	"\tRecognize\x12\x18.lpr.v1.RecognizeRequest\x1a\x19.lpr.v1.RecognizeResponse\x12<\n" +
	"\vHealthCheck\x12\x15.lpr.v1.HealthRequest\x1a\x16.lpr.v1.HealthResponseB>Z<github.com/jabar-creative/parkir/edge-api/internal/lpr/lprpbb\x06proto3"

var (
	file_lpr_proto_rawDescOnce sync.Once
	file_lpr_proto_rawDescData []byte
)

func file_lpr_proto_rawDescGZIP() []byte {
	file_lpr_proto_rawDescOnce.Do(func() {
		file_lpr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lpr_proto_rawDesc), len(file_lpr_proto_rawDesc)))
	})
	return file_lpr_proto_rawDescData
}

var file_lpr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lpr_proto_goTypes = []any{
	(*RecognizeRequest)(nil),  // 0: lpr.v1.RecognizeRequest
	(*RecognizeResponse)(nil), // 1: lpr.v1.RecognizeResponse
	(*HealthRequest)(nil),     // 2: lpr.v1.HealthRequest
	(*HealthResponse)(nil),    // 3: lpr.v1.HealthResponse
}
var file_lpr_proto_depIdxs = []int32{
	0, // 0: lpr.v1.LPR.Recognize:input_type -> lpr.v1.RecognizeRequest
	2, // 1: lpr.v1.LPR.HealthCheck:input_type -> lpr.v1.HealthRequest
	1, // 2: lpr.v1.LPR.Recognize:output_type -> lpr.v1.RecognizeResponse
	3, // 3: lpr.v1.LPR.HealthCheck:output_type -> lpr.v1.HealthResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lpr_proto_init() }
func file_lpr_proto_init() {
	if File_lpr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lpr_proto_rawDesc), len(file_lpr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lpr_proto_goTypes,
		DependencyIndexes: file_lpr_proto_depIdxs,
		MessageInfos:      file_lpr_proto_msgTypes,
	}.Build()
	File_lpr_proto = out.File
	file_lpr_proto_goTypes = nil
	file_lpr_proto_depIdxs = nil
}
