// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: lpr.proto

package lprpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LPR_Recognize_FullMethodName   = "/lpr.v1.LPR/Recognize"
	LPR_HealthCheck_FullMethodName = "/lpr.v1.LPR/HealthCheck"
)

// LPRClient is the client API for LPR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LPR service — deteksi kendaraan + OCR plat. PRD §7.1. Deadline 1000 ms (NFR-1.1).
type LPRClient interface {
	Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error)
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type lPRClient struct {
	cc grpc.ClientConnInterface
}

func NewLPRClient(cc grpc.ClientConnInterface) LPRClient {
	return &lPRClient{cc}
}

func (c *lPRClient) Recognize(ctx context.Context, in *RecognizeRequest, opts ...grpc.CallOption) (*RecognizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecognizeResponse)
	err := c.cc.Invoke(ctx, LPR_Recognize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lPRClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LPR_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LPRServer is the server API for LPR service.
// All implementations must embed UnimplementedLPRServer
// for forward compatibility.
//
// LPR service — deteksi kendaraan + OCR plat. PRD §7.1. Deadline 1000 ms (NFR-1.1).
type LPRServer interface {
	Recognize(context.Context, *RecognizeRequest) (*RecognizeResponse, error)
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedLPRServer()
}

// UnimplementedLPRServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLPRServer struct{}

func (UnimplementedLPRServer) Recognize(context.Context, *RecognizeRequest) (*RecognizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recognize not implemented")
}
func (UnimplementedLPRServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedLPRServer) mustEmbedUnimplementedLPRServer() {}
func (UnimplementedLPRServer) testEmbeddedByValue()             {}

// UnsafeLPRServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LPRServer will
// result in compilation errors.
type UnsafeLPRServer interface {
	mustEmbedUnimplementedLPRServer()
}

func RegisterLPRServer(s grpc.ServiceRegistrar, srv LPRServer) {
	// If the following call panics, it indicates UnimplementedLPRServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LPR_ServiceDesc, srv)
}

func _LPR_Recognize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecognizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LPRServer).Recognize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LPR_Recognize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LPRServer).Recognize(ctx, req.(*RecognizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LPR_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LPRServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LPR_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LPRServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LPR_ServiceDesc is the grpc.ServiceDesc for LPR service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LPR_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lpr.v1.LPR",
	HandlerType: (*LPRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Recognize",
			Handler:    _LPR_Recognize_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _LPR_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lpr.proto",
}
